### ISSUE TITLE
Provide access to history object

### ISSUE THREAD

**Issue by Gollum999** [retejs/history-plugin#2]
I would like to be able to modify actions in the history under certain circumstances.  (Similar to how the code that sets up `DragNodeAction` combines multiple node moves into a single action.)

As far as I can tell, there is no way to get at the `History` object in client code.

A couple of potential ideas:

- Let the `install` function of all plugins return something to the caller, which could be stored alongside `options` in `Context.plugins`.
- Store a reference to `history` inside `Action`, setting the value when `'addhistory'` is triggered.

**Comment by Ni55aN** [comment]
What exactly do you want to implement?

**Comment by Gollum999** [comment]
In my case, I have a (probably overcomplicated) system where socket types can change based on user input.  These type changes can cascade down the graph, and if any existing connection becomes incompatible, it will be automatically removed.

My problem is that if this happens and then I hit "Undo", Rete will try to reconnect any connections that were automatically removed before unwinding back to the original event that caused the sockets to be incompatible in the first place.  So to the user it appears that the "Undo" does nothing, and if they undo enough to get back to that original event, the graph won't be in the same state it was in originally, because those connections failed to be reestablished.

Essentially my plan is to "bundle" these events into a single action, but to do so will I need to "squash" all of the automated `RemoveConnectionActions` into my own custom action that handles everything at the same time.

I suppose another option would be to remove the `'connectionremoved'` event handler that is provided by this plugin and always handle those events myself, which would let me prevent those actions from being added to the stack in the first place.  Seems like a bit of a hack, but it might work if providing access to `History` is undesirable.

**Comment by Ni55aN** [comment]
>  socket types can change based on user input

Does this user input have a history action?

**Comment by Gollum999** [comment]
Yes.

**Comment by Ni55aN** [comment]
> Rete will try to reconnect any connections that were automatically removed before unwinding back to the original event that caused the sockets to be incompatible in the first place

Your action should to change socket type on undo() and redo()

**Comment by Gollum999** [comment]
Hmm... I think that would work, but only if I enforce that the user action is added to the stack *after* all bad connections are removed.  Right now I make all of my changes in the nodes' `worker` functions, so I don't have a ton of freedom over the order that those things happen, but if I traverse the graph myself that should theoretically work.

Outside of this example, another potential use case for access to the `History` object would be to display the current undo/redo stack to the user.  In that case, I guess the alternative would be to add handlers for `'addhistory'`/`'undo'`/`'redo'` and track a copy of the stack by hand.

Regardless, I think I at least have something to work with now.  Thanks!

**Comment by Ni55aN** [comment]
>  Right now I make all of my changes in the nodes' worker

Do you change the socket type in `worker()`?. I assume that this is a bad practice, since the worker is intended to process data without changing the scheme nodes and connections.

**Comment by Gollum999** [comment]
Yes.  I agree that it probably is bad practice and it has been on my list of things to clean up for a little while now.  Hopefully getting undo/redo working will give me a good excuse to get in there and do things the right way this time.

**Comment by Ni55aN** [comment]
Please share a minimal example on codepen/codesandbox

**Comment by codeart1st** [comment]
Another use case in my opinion is for dedicated undo and redo buttons. It would be nice to disable the buttons related to the items in the history object. For this usecase additional events are also an option to implement.

**Comment by dlohvinov** [comment]
@Ni55aN hi!
I can relate to this question https://github.com/retejs/history-plugin/issues/2#issuecomment-1025087325

can I make a pull request with exposing of history object and getters for `allowUndo`/`allowRedo`? :)

**Comment by Ni55aN** [comment]
@dlohvinov exposing History instance isn't a good idea, but you can expose its readonly copy of `produced` array. Probably no needs for allowUndo/allowRedo

**Comment by dlohvinov** [comment]
@Ni55aN okay, I will try it and make a pull request :)
thank you!

Am I understand you correctly: you don't want to expose History instance so that actual user won't break it's logic by himself, yep?

**Comment by Ni55aN** [comment]
> you don't want to expose History instance so that actual user won't break it's logic by himself, yep?

correct, but mostly because of avoiding breaking changes

**Comment by dlohvinov** [comment]
@Ni55aN hi!
I'm having issues implementing readonly `produced`/`reserved` copies exposed: it's way harder than I first thought it would be and I'm not sure I'm doing it right :(

I can't just expose `Object.freeze`ed arrays, because then main array becomes freezed.
So that I should first make it's copy and freeze it deeply (+1 npm dependency, x2 memory).
So that I should update this copy anytime original arrays are updated.
So that I should also implement subscription mechanism to update these copies (or update them on `editor` `undo`/`redo`/`addhistory' events).

I can do this, no problem, but it sounds quite complicated for me, like overengeneering.
Maybe you have some thoughts on this?

**Comment by Ni55aN** [comment]
@dlohvinov by 'readonly' I meant that the interface shouldn't give a chance to modify these arrays. For example, it can just return copies of arrays

**Comment by dlohvinov** [comment]
@Ni55aN sorry for misunderstanding, I didn't mean to say that "this way is bad, let's just expose history!".
I ment I thought about solution and it seems quite complicated for me and maybe I'm doing something wrong so that I hoped you would suggest a better solution :)

**Comment by Ni55aN** [comment]
@dlohvinov no need to apologize))) It was just reasoning that there's no single right solution
