### ISSUE TITLE
History actions count restriction

### ISSUE THREAD

**Issue by dlohvinov** [retejs/history-plugin#22]
Hi!

First of all, thank you for the great plugin!
In my project, I need an ability to restrict a count of stored history actions. I've downloaded this plugin and implemented it for myself, but, I suppose, it would be great if original plugin will have this functionality too. 

Don't you mind if I will make a pull request with this feature?

Thanks for your response! 💛💙

**Comment by dlohvinov** [comment]
Also I encountered an issue that Cmd+Z Cmd+Y, which are default undo-redo controls on MacOS, doesn't work. Shall I make a pull request to fix this issue too?

**Comment by Ni55aN** [comment]
Yes, sure, you can create a separate PRs

**Comment by dlohvinov** [comment]
@Ni55aN here's the first one :)

**Comment by Ni55aN** [comment]
released in v0.2.3
