### ISSUE TITLE
Undo event arguments

### ISSUE THREAD

**Issue by Baseetai** [retejs/history-plugin#3]
Thanks for very nice library and for you continues  support,

My question is about `editor.on('undo', (p1) => {})`.  I'm receiving an empty object here `p1`, is this ok ?
I expect the object to describe the action.

**Comment by Ni55aN** [comment]
`undo`/`redo` events don't have any arguments.
These events are listened under the hood

https://github.com/retejs/history-plugin/blob/f977c9e72fa2af6d946fc649a395cea704b6fe82/src/index.js#L29-L30
