### ISSUE TITLE
clear history on import

### ISSUE THREAD

**Issue by Ni55aN** [retejs/history-plugin#4]

**Comment by agrawalankush** [comment]
Any plans on working on this issue? If not can you describe how do I go about to implement this?

**Comment by Ni55aN** [comment]
@agrawalankush this issue is related to https://github.com/retejs/history-plugin/issues/5

The editor triggers [clear event](https://github.com/retejs/rete/blob/master/src/editor.ts#L112) on import.  You can listen to this event and clear history's produced and reserved

**Comment by agrawalankush** [comment]
Let me know if you meant or expecting something else! I'll make the change!
https://github.com/retejs/history-plugin/pull/13/files

**Comment by Ni55aN** [comment]
Commented, everything is fine other than formatting

**Comment by Ni55aN** [comment]
@agrawalankush commented, everything is fine other than formatting

**Comment by agrawalankush** [comment]
Added formatting changes!

**Comment by Ni55aN** [comment]
https://github.com/retejs/history-plugin/issues/5#issuecomment-834182748
