### ISSUE TITLE
Undo/Redo does not work well with editor.clear()

### ISSUE THREAD

**Issue by tomgutz** [retejs/history-plugin#5]
Hi, thank you for the plugin.

For the issue. I believe the plugin does not properly add the history for the clear action that is called with the editor engine itself. Plugin may need to integrate it better with the editor action such as clear. Which clears/resets the stage/graph/

**Comment by Ni55aN** [comment]
Fixed in v0.2.2

Example: https://codepen.io/Ni55aN/pen/MWpYbbw
